name: Deploy MLOps 1

on:
  workflow_dispatch:

env:
  S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy S3 bucket (dev)
        run: |
          echo "ðŸš€ START - S3 Bucket Deployment"
          aws cloudformation deploy \
            --parameter-overrides BucketName=$S3_BUCKET_NAME \
            --template-file infra/cloudformation/s3_bucket.yaml \
            --stack-name mlops-s3 \
            --capabilities CAPABILITY_NAMED_IAM
          echo "âœ… END - S3 Bucket Deployment"

      - name: Deploy ECR repository
        run: |
          echo "ðŸš€ START - ECR Repo Deployment"
          aws cloudformation deploy \
            --template-file infra/cloudformation/ecr.yaml \
            --stack-name mlops-ecr
          echo "âœ… END - ECR Repo Deployment"

      - name: Deploy ECS Cluster
        run: |
          echo "ðŸš€ START - ECS Cluster Deployment"
          aws cloudformation deploy \
            --template-file infra/cloudformation/ecs_cluster.yaml \
            --stack-name mlops-ecs-cluster
          echo "âœ… END - ECS Cluster Deployment"

      - name: Deploy ECS Task Definition
        run: |
          echo "ðŸš€ START - ECS Task Definition Deployment"
          aws cloudformation deploy \
            --template-file infra/cloudformation/ecs_task.yaml \
            --stack-name mlops-task \
            --capabilities CAPABILITY_IAM
          echo "âœ… END - ECS Task Definition Deployment"

